sap.ui.define([
	"sap/ui/model/json/JSONModel",
	"sap/ui/Device"
], function (JSONModel, Device) {
	"use strict";

	return {
		createDeviceModel : function () {
			var oModel = new JSONModel(Device);
			oModel.setDefaultBindingMode("OneWay");
			return oModel;
		},
		
		createGlobalModel: function() {
			var oModel = new JSONModel({
				users: [],
				pools: [],
				simCockpitSelectedYear: "",
				simCockpitUsers: [],
				selectedRM: [],
				selectedPool: [],
				poolProfile: [],
				newPoolCompParams: [],
				newPoolMembers: [],
				relevantPoolMembers: [],
				kpiCorrectionsPool: [],
				limitedPoolKpiRecognition: [],
				poolBusinessCases: [],
				compensationProfile: [],
				compensationParams: [],
				compElements: [],
				compensationNotes : [],
				modelSelection: [],
				relationshipManager: [],
				approvingManagers: [],
				transferredAccounts: [],
				kpiCorrections: [],
				exclusions: [],
				businessCase: [],
				limitedKpiRecognition: [],
				compProfileBusy: false,
				compNotesBusy: false,
				kpiRowSelected: false,
				scoreCardPeriod: "",
				selectedScoreCard: [],
				selectedScColumnsItems: [],
				selectedScItems: [],
				calcButtonStatus: [],
				calculationBusy: false,
				itaRowSelected: false,
				poolWizardData: [],
				prospects: [],
				poolTransferredAccounts: [],
				poolLimitedKPIRecognition: [],
				poolKPIExceptions: [],
				poolBusinessCase: [],
				poolKPIRowSelected: false,
				poolITABusy: false,
				ITABusy: false,
				rmCompParamsEnabled: false,
				rmFieldStates: [],
				decEAMsPeriodBusy: false,
				poolDecentralizedEAMs: [],
				decentralizedEAMs: [],
				decPoolEAMsPeriodBusy: false,
				reports: [],
				selectedReport: [],
				maintainTransferredAccounts: [],
				selectedMaintainITA: [],
				poolBusy: false,
				cleanup: [],
				copyProfiles: [],
				copyProfilesFrom: "",
				copyProfilesTo: "",
				copyBusy: false,
				release: [],
				resetRequest: [],
				mdCurrencies: [],
				mdRegions: [],
				mdYears: [],
				authorize: [],
				authorizeProfitSelected: false,
				authorizeOrgSelected: true,
				mta: [],
				approvalTxt: "",
				rejectionTxt: "",
				selectedProspect: [],
				prospectBusinessCase: [],
				prospectProfileBusy: false,
				cce: [],
				prospectFieldStates: [],
				locations: [],
				cleanupPoolsUsers: [],
				RmMTA: "",
				kriResult: [],
				policyProcedureDeduction: "",
				thKRIDeduction: "",
				milestones: [],
				milestoneButtonsVisible: false,
				conditionVisible: false,
				selectedMilestoneId: "",
				conductAssessment: [],
				nonFinGoal: "",
				custCompModel: [],
				custCompParams: [],
				custGrowthRate: [],
				custPayoutCurves: [],
				custSimCurrency: [],
				custGrowthRateAbs: [],
				custFirstYearSim: [],
				selectedCustomEntity: "",
				simToolPeriod: "",
				calcSimButtonStatus: [],
				simToolBusy: false,
				combinedFiltersKey: ""
			})
			return oModel;
		}
	};

});